config/routes.rb
Rails.application.routes.draw do
  root :to => 'search#movie'

  get 'search/people'
  get 'search/tv'
  get 'search/movie'

  get 'search/people/:id' => 'search#people_detail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_cast
  has_many :movie_crew
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :person
  belongs_to :movie
end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :person
  belongs_to :movie
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
end

app/models/movie_person.rb
class MoviePerson < ApplicationRecord
end

app/models/network.rb
class Network < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :movie_cast
  has_many :movie_crew

  has_many :person_as_name
end

app/models/tv.rb
class Tv < ApplicationRecord
  has_many :tv_cast
  has_many :tv_crew
end

app/models/tv_cast.rb
class TvCast < ApplicationRecord
  belongs_to :tv
  belongs_to :person
end

app/models/tv_company.rb
class TvCompany < ApplicationRecord
  belongs_to :tv
  belongs_to :company
end

app/models/tv_crew.rb
class TvCrew < ApplicationRecord
  belongs_to :tv
  belongs_to :person
end

app/models/tv_episode.rb
class TvEpisode < ApplicationRecord
end

app/models/tv_genre.rb
class TvGenre < ApplicationRecord
end

app/models/tv_network.rb
class TvNetwork < ApplicationRecord
  belongs_to :tv
  belongs_to :network
end

app/models/tv_person.rb
class TvPerson < ApplicationRecord
end

app/models/tv_season.rb
class TvSeason < ApplicationRecord
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  PAGE_COUNT = 20
  PAGINATION = 3

  def movie
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @no = (@page - 1) * PAGE_COUNT
    sort = params[:sort] || 'title'
    order = params[:order] == 'desc' ? :desc : :asc

    @movies = Movie
      .where(
        "title like :query or original_title like :query",
        { :query => "%#{params[:query]}%" }
      )
      .left_outer_joins(movie_cast: :person)
      .group(:id)
      .order({ sort => order })
      .limit(PAGE_COUNT).offset((@page - 1) * PAGE_COUNT)

    count = Movie.where(
      "title like :query or original_title like :query",
      { :query => "%#{params[:query]}%" }
    )
    .left_outer_joins(movie_cast: :person)
    .group(:id).length
      
    @last = [1, (count.to_f / PAGE_COUNT).ceil].max

    @start = [1, @page - PAGINATION].max
    @end = [@last, @page + PAGINATION].min
  end
  
  def tv
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @no = (@page - 1) * PAGE_COUNT
    sort = params[:sort] || 'name'
    order = params[:order] == 'desc' ? :desc : :asc

    @tvs = Tv
      .where(
        "name like :query or original_name like :query",
        { :query => "%#{params[:query]}%" }
      )
      .order({ sort => order })
      .limit(PAGE_COUNT).offset((@page - 1) * PAGE_COUNT)

    count = Tv.where(
      "name like :query or original_name like :query",
      { :query => "%#{params[:query]}%" }
    ).length
      
    @last = [1, (count.to_f / PAGE_COUNT).ceil].max

    @start = [1, @page - PAGINATION].max
    @end = [@last, @page + PAGINATION].min
  end

  def people
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @no = (@page - 1) * PAGE_COUNT
    sort = params[:sort] || 'name'
    order = params[:order] == 'desc' ? :desc : :asc

    @people = Person
      .where(
        "name like :query",
        { :query => "%#{params[:query]}%" }
      )
      .order({ sort => order })
      .limit(PAGE_COUNT).offset((@page - 1) * PAGE_COUNT)

    count = Person.where(
      "name like :query",
      { :query => "%#{params[:query]}%" }
    ).length
      
    @last = [1, (count.to_f / PAGE_COUNT).ceil].max

    @start = [1, @page - PAGINATION].max
    @end = [@last, @page + PAGINATION].min
  end

  def people_detail
    @person = Person.where("`people`.`id` = :id", { :id => params[:id] }).left_outer_joins(:person_as_name).group(:id).take

    render template: "search/people.detail.html.erb"
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def page_params
    request.params.slice("query", "sort", "page")
  end

  def toggleOrder
    params[:order] == 'desc' ? 'asc' : 'desc'
  end

  def displayOrderMovieAngle(name)
    displayOrderAngle(name, 'title')
  end

  def displayOrderTvAngle(name)
    displayOrderAngle(name, 'name')
  end

  def displayOrderPeopleAngle(name)
    displayOrderAngle(name, 'name')
  end

  def displayOrderAngle(name, default)
    sort = params[:sort] || default
    if sort == name
      if params[:order] == 'desc'
        return '<i class="disabled angle up icon"></i>'.html_safe
      else 
        return '<i class="disabled angle down icon"></i>'.html_safe
      end
    end
  end
end

app/views/search/movie.html.erb
<div class="ui grid">
  <div class="six wide column">
    <h2>Movies</h2>
  </div>
  <div class="ten wide column">
    <%= form_tag('/search/movie', { :method => 'GET', :class => "ui form" }) do %>
      <div class="field">
        <div class="ui action input">
          <%= text_field_tag('query', params[:query]) %>
          <button class="ui button">Search</button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="ui celled table">
  <thead>
    <tr>
      <th>#</th>
      <th>
        <%= link_to "제목", search_movie_path(page_params.merge(:sort => 'title', :order => toggleOrder)) %>
        <%= displayOrderMovieAngle('title') %>
      </th>
      <th>
        <%= link_to "인기도", search_movie_path(page_params.merge(:sort => 'popularity', :order => toggleOrder)) %>
        <%= displayOrderMovieAngle('popularity') %>
      </th>
      <th>
        <%= link_to "평점", search_movie_path(page_params.merge(:sort => 'vote_average', :order => toggleOrder)) %>
        <%= displayOrderMovieAngle('vote_average') %>
      </th>
      <th>배우</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <% casts = movie.movie_cast %>
      <tr>
        <td data-label="No"><%= @no += 1 %></td>
        <td data-label="Title"><%= movie["original_title"] %></td>
        <td data-label="Popularity"><%= movie["popularity"] %></td>
        <td data-label="Average"><%= movie["vote_average"] %></td>
        <td data-label="Casts">
          <% casts.each do |cast| %>
            <ul>
              <li>
                <%= link_to cast.person["name"], controller:'search', action: 'people_detail', id: cast.person["id"] %>
              </li>
            </ul>
          <% end %>
        </td>
      </tr>
    <%end %>
    
    <% if @movies.blank? %>
      <tr>
        <td>검색 결과가 없습니다.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="ui pagination menu">
  <% if @start != 1 %>
    <%= link_to 1, search_movie_path(page_params.merge(:page => 1)), :class => @page == 1 ? "item active" : "item" %>
  <% end %>

  <% if @start > 2 %>
    <div class="disabled item">...</div>
  <% end %>

  <% for p in (@start..@end).to_a %>
    <%= link_to p, search_movie_path(page_params.merge(:page => p)), :class => @page == p ? "item active" : "item" %>
  <% end %>
  
  <% if @end < @last - 1 %>
    <div class="disabled item">...</div>
  <% end %>

  <% if @end != @last %>
    <%= link_to @last, search_movie_path(page_params.merge(:page => @last)), :class => @page == @last ? "item active" : "item" %>
  <% end %>
</div>

app/views/search/people.detail.html.erb
<h2><%= @person["name"] %></h2>

<% if not @person["biography"].blank? %>
  <h3>소개:</h3>
  <p><%= @person["biography"] %></p>
<% end %>

<% if not @person["known_for_department"].blank? %>
  <h3>직업: <span><%= @person["known_for_department"] %></span></h3>
<% end %>

<% if not @person["deathday"].blank? %>
  <h3>사망일: <span><%= @person["deathday"] %></span></h3>
<% end %>

<% if @person["gender"] != 0 %>
  <h3>성별: <span><%= @person["gender"] == 1 ? '여자' : '남자' %></span></h3>
<% end %>

<% if not @person["popularity"].blank? %>
  <h3>인기도: <span><%= @person["popularity"] %></span></h3>
<% end %>

<% if not @person["place_of_birth"].blank? %>
  <h3>태어난 장소: <span><%= @person["place_of_birth"] %></span></h3>
<% end %>

<% if not @person.person_as_name.blank? %>
  <h3>불리는 이름</h3>
  <ul class="ui list">
    <% for name in @person.person_as_name %>
      <li><%= name["name"] %></li>
    <% end %>
  </ul>
<% end %>

app/views/search/people.html.erb
<div class="ui grid">
  <div class="six wide column">
    <h2>People</h2>
  </div>
  <div class="ten wide column">
    <%= form_tag('/search/people', { :method => 'GET', :class => "ui form" }) do %>
      <div class="field">
        <div class="ui action input">
          <%= text_field_tag('query', params[:query]) %>
          <button class="ui button">Search</button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="ui celled table">
  <thead>
    <tr>
      <th>#</th>
      <th>
        <%= link_to "이름", search_people_path(page_params.merge(:sort => 'name', :order => toggleOrder)) %>
        <%= displayOrderPeopleAngle('name') %>
      </th>
      <th>
        <%= link_to "인기도", search_people_path(page_params.merge(:sort => 'popularity', :order => toggleOrder)) %>
        <%= displayOrderPeopleAngle('popularity') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td data-label="No"><%= @no += 1 %></td>
        <td data-label="Name">
          <%= link_to person["name"], controller:'search', action: 'people_detail', id: person["id"] %>
        </td>
        <td data-label="Popularity"><%= person["popularity"] %></td>
      </tr>
    <%end %>
    
    <% if @people.blank? %>
      <tr>
        <td>검색 결과가 없습니다.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="ui pagination menu">
  <% if @start != 1 %>
    <%= link_to 1, search_people_path(page_params.merge(:page => 1)), :class => @page == 1 ? "item active" : "item" %>
  <% end %>

  <% if @start > 2 %>
    <div class="disabled item">...</div>
  <% end %>

  <% for p in (@start..@end).to_a %>
    <%= link_to p, search_people_path(page_params.merge(:page => p)), :class => @page == p ? "item active" : "item" %>
  <% end %>
  
  <% if @end < @last - 1 %>
    <div class="disabled item">...</div>
  <% end %>

  <% if @end != @last %>
    <%= link_to @last, search_people_path(page_params.merge(:page => @last)), :class => @page == @last ? "item active" : "item" %>
  <% end %>
</div>

app/views/search/tv.html.erb
<div class="ui grid">
  <div class="six wide column">
    <h2>TVs</h2>
  </div>
  <div class="ten wide column">
    <%= form_tag('/search/tv', { :method => 'GET', :class => "ui form" }) do %>
      <div class="field">
        <div class="ui action input">
          <%= text_field_tag('query', params[:query]) %>
          <button class="ui button">Search</button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="ui celled table">
  <thead>
    <tr>
      <th>#</th>
      <th>
        <%= link_to "제목", search_tv_path(page_params.merge(:sort => 'name', :order => toggleOrder)) %>
        <%= displayOrderTvAngle('name') %>
      </th>
      <th>
        <%= link_to "인기도", search_tv_path(page_params.merge(:sort => 'popularity', :order => toggleOrder)) %>
        <%= displayOrderTvAngle('popularity') %>
      </th>
      <th>
        <%= link_to "평점", search_tv_path(page_params.merge(:sort => 'vote_average', :order => toggleOrder)) %>
        <%= displayOrderTvAngle('vote_average') %>
      </th>
      <th>배우</th>
    </tr>
  </thead>
  <tbody>
    <% @tvs.each do |tv| %>
      <% casts = tv.tv_cast %>
      <tr>
        <td data-label="No"><%= @no += 1 %></td>
        <td data-label="Name"><%= tv["original_name"] %></td>
        <td data-label="Popularity"><%= tv["popularity"] %></td>
        <td data-label="Average"><%= tv["vote_average"] %></td>
        <td data-label="Casts">
          <% casts.each do |cast| %>
            <ul>
              <li>
                <%= link_to cast.person["name"], controller:'search', action: 'people_detail', id: cast.person["id"] %>
              </li>
            </ul>
          <% end %>
        </td>
      </tr>
    <%end %>
    
    <% if @tvs.blank? %>
      <tr>
        <td>검색 결과가 없습니다.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="ui pagination menu">
  <% if @start != 1 %>
    <%= link_to 1, search_tv_path(page_params.merge(:page => 1)), :class => @page == 1 ? "item active" : "item" %>
  <% end %>

  <% if @start > 2 %>
    <div class="disabled item">...</div>
  <% end %>

  <% for p in (@start..@end).to_a %>
    <%= link_to p, search_tv_path(page_params.merge(:page => p)), :class => @page == p ? "item active" : "item" %>
  <% end %>
  
  <% if @end < @last - 1 %>
    <div class="disabled item">...</div>
  <% end %>

  <% if @end != @last %>
    <%= link_to @last, search_tv_path(page_params.merge(:page => @last)), :class => @page == @last ? "item active" : "item" %>
  <% end %>
</div>